name: kinde_flutter_sdk
description: The Kinde SDK For Flutter.
version: 1.0.3
homepage: https://github.com/kinde-oss/kinde-flutter-sdk

environment:
  sdk: '>=2.15.0 <4.0.0'
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter

  pubspec_parse: ^1.2.1
  flutter_appauth: ^6.0.1
  flutter_custom_tabs: ^2.0.0 ///use browser:1.8.0
  flutter_inappwebview: ^6.0.0
  hive: ^2.2.3
  flutter_secure_storage: ^8.0.0
  path_provider: ^2.0.15
  dio: ^5.0.0
  jose: ^0.3.3
  one_of: '>=1.5.0 <2.0.0'
  one_of_serializer: '>=1.5.0 <2.0.0'
  built_value: '>=8.4.0 <9.0.0'
  built_collection: '>=5.1.1 <6.0.0'
  mockito: ^5.4.2
  kinde_flutter_sdk_platform_interface:
    path: kinde_flutter_sdk_platform_interface
#  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  built_value_generator: '>=8.4.0 <9.0.0'
  build_runner: any
  test: ^1.16.0

flutter:
  plugin:
    platforms:
      android:
        pluginClass: KindeFlutterSdkPlugin
        default_package: kinde_flutter_sdk_android
      ios:
        pluginClass: KindeFlutterSdkPlugin
        default_package: kinde_flutter_sdk_ios
      macos:
        pluginClass: KindeFlutterSdkPlugin
        default_package: kinde_flutter_sdk_macos
      web:
        default_package: kinde_flutter_sdk_web
